---
# Location where configuration files will be stored.
config_dir: '~'

# Server IP
hostname: "server.home"
timezone: Europe/Paris

# Homepage configuration
homepage_enable: false

# DNS configuration
dns_enable: false
pihole_password: "change-this-password"

# Monitoring backend configuration
monitoring_enable: false
monitoring_grafana_admin_user: "admin"
monitoring_grafana_admin_password: "change-this-password"
monitoring_influxdb_user: "admin"
monitoring_influxdb_password: "change-this-password"
monitoring_influxdb_bucket: "bucket"
monitoring_influxdb_retention: "4w" 