---
- name: Setup docker containers for homelab architectures
  hosts: all
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - default.config.yaml
        - config.yaml

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yaml

  tasks:
    - name: Set up Homepage.
      ansible.builtin.include_tasks: tasks/homepage.yaml
      when: homepage_enable

    - name: Set up DNS.
      ansible.builtin.include_tasks: tasks/dns.yaml
      when: dns_enable

    - name: Set up monitoring backend.
      ansible.builtin.include_tasks: tasks/monitoring_backend.yaml
      when: monitoring_enable
