---
- name: Restart dns
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/dns/"
    build: false
    restarted: true
  become: false

- name: Restart monitoring-backend
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring_backend/"
    build: false
    restarted: true
  become: false
