---
- name: Create monitoring backend folders.
  become: false
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ config_dir }}/monitoring_backend/"
    - "{{ config_dir }}/monitoring_backend/grafana/"
    - "{{ config_dir }}/monitoring_backend/influxdb/"
    - "{{ config_dir }}/monitoring_backend/speedtest/"
    - "{{ config_dir }}/monitoring_backend/mosquitto/"

- name: Copy monitoring backend docker-compose to Pi.
  become: false
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/monitoring_backend/{{ item.dest }}"
    mode: '0644'
  notify: Restart monitoring-backend
  loop:
    - src: monitoring-docker-compose.yaml.j2
      dest: docker-compose.yaml

- name: Ensure Grafana is running.
  become: false
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring_backend/"
    build: false
