---
- name: Create monitoring backend folders.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  become: false
  loop: 
    - "{{ config_dir }}/monitoring_backend/"
    - "{{ config_dir }}/monitoring_backend/grafana/"

- name: Copy monitoring backend docker-compose to Pi.
  ansible.builtin.template:
    src: templates/monitoring-docker-compose.yaml.j2
    dest: "{{ config_dir }}/monitoring_backend/docker-compose.yaml"
    mode: '0640'
  notify: Restart monitoring-backend
  become: false

- name: Ensure Grafana is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/monitoring_backend/"
    build: false
  become: false